#!/usr/bin/env ruby
# encoding: utf-8
require_relative 'lib/sist'
Dir['spec/*.in'].each do |e|
  name = e.sub /spec\/(.+)\.in/ do $1.capitalize end
  puts "- #{name}"
  File.readlines(e).each do |eg|
    eg.chomp!
    cleaned = Sist.sanitize eg
    puts "    - `#{eg}` ⇒ `#{cleaned}`"
  end
end
